resilience4j.ratelimiter.instances.loginLimiter.limitForPeriod: 5
resilience4j.ratelimiter.instances.loginLimiter.limitRefreshPeriod: 60s
resilience4j.ratelimiter.instances.loginLimiter.timeoutDuration: 0


resilience4j:
  circuitbreaker:
    instances:
      getAllUsersCB:
        slidingWindowSize: 5
        failureRateThreshold: 10
        waitDurationInOpenState: 5s